[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = {version = "4"}
actix-cors = "0.6"
diesel = { version = "1.4.8", features = ["postgres", "r2d2",] }
dotenv = "0.15.0"
r2d2 = "0.8.9"