name: Deploy Frontend React app to  GitHub Pages

permissions:
  contents:
    write 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # see how to change and sync devcontainer/local docker file definition eventually

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build the app
        run: cd frontend && npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages
        with:
          path: .frontend/build